Update mlflow-ci.yml

diff --git a/.github/workflows/mlflow-ci.yml b/.github/workflows/mlflow-ci.yml
--- a/.github/workflows/mlflow-ci.yml
+++ b/.github/workflows/mlflow-ci.yml
@@ -47,11 +47,12 @@ jobs:
       - name: Get latest MLflow run_id
         id: get_run_id
         run: |
-          RUN_ID=$(ls -td MLProject/mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
+          cd MLProject
+          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
 
           if [ -z "$RUN_ID" ]; then
-            echo "FATAL ERROR: RUN_ID tidak ditemukan."
-            exit 1
+          echo "FATAL ERROR: RUN_ID tidak ditemukan."
+          exit 1
           fi
 
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
